
version: '3.9'
services:
  node:
    image: node
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT_NODE}
    ports:
      - "${PORT_NODE}:${PORT_NODE}"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"